#!/usr/bin/env bash

set -au

# We default the GitHub user here, as the script is for me.
GH_USER="${GH_USER:-Nilstrieb}"

# Reset the option index for getopts parsing below.
OPTIND=1

ESC=$(printf '\e')

# Show help if the -h flag is passed.
while getopts "h?:" opt; do
    case "$opt" in
        h)
            cat <<EOF
git hack-rlo

Usage: git hack-rlo [OPTIONS]

Shows information about developing in the rust-lang GitHub org, mainly the rust repository.

Options:
  -h     Get help, shows this page
EOF
            exit
            ;;
    esac
done

# Calls the GitHub search endpoint with a query that is passed as the first argument.
github_search_fetch() {
    curl -Ls \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        "https://api.github.com/search/$1"
}

# Pretty prints a JSON list from the GitHub search endpoint.
pretty_print_list() {
    # https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda
    # Example:
    # 2023-03-09T21:38:07Z 24💬 Add `internal_features` lint
    echo "$1" | jq ".items[] | \"\(.created_at) \(.comments)💬 $ESC]8;;\(.url | sub(\"api.\";\"\") | sub(\"/repos\";\"\"))$ESC\\\\\(.title)$ESC]8;;$ESC\\\\\"" -r
}

# Print all PRs that match a query. The GitHub Search API query may be different from the web UI query,
# which is why they are passed as separate arguments.
show_prs() {
    api_query=$1
    web_query=$2
    prompt=$3

    own_prs=$(github_search_fetch "$api_query")
    echo "$prompt"
    pretty_print_list "$own_prs"
    echo "Open full list on GitHub? (y/n)"
    read OPEN
    if [ "$OPEN" = "y" ]; then
        open "https://github.com/rust-lang/rust/pulls?q=$web_query"
    fi
}

show_prs "issues?q=state%3Aopen%20author%3A$GH_USER%20type%3Apr%20org%3Arust-lang%20label%3AS-waiting-on-author" \
    "is%3Aopen+is%3Apr+author%3A$GH_USER+label%3AS-waiting-on-author" \
    "Own PRs waiting on author"

show_prs "issues?q=state%3Aopen%20assignee%3A$GH_USER%20type%3Apr%20org%3Arust-lang%20label%3AS-waiting-on-review" \
    "is%3Aopen+is%3Apr+assignee%3A$GH_USER+label%3AS-waiting-on-review" \
    "Assigned PRs waiting on review"
